### ISSUE TITLE
Only show WSPR spots in same band

### ISSUE THREAD

**Issue by ve1vdm** [swharden/FSKview#10]

**Comment by ve1vdm** [comment]
Scott is there a way there could be a " clear screen " button that would remove all data from the screen during a frequency change. I know that one could exit and restart but just wondering how hard it would be to implement.

**Comment by swharden** [comment]
Although not displayed on the spectrogram, the program is aware of the frequency of every WSPR spot. Perhaps I could have it only show spots in the same band as the dial frequency?

![image](https://user-images.githubusercontent.com/4165489/86277871-72e79900-bba5-11ea-837b-bcce1dd5d73f.png)

Note to self, add another `Where` statement to check frequency by editing this line
https://github.com/swharden/FSKview/blob/38f0d01a10050ecc5a762bf3ef29dbe0c57d9e66/src/FSKview/FormMain.cs#L147

**Comment by swharden** [comment]
done, will be in next version
