### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#14]
Is there a way to show received time on the vertical or horizontal axis?

**Comment by swharden** [comment]
Right now there is not, but the way FSKview is designed it is not necessary. 

Every image is exactly 10 minutes wide, so left to right always spans x0:00 to x9:99, and there will always be exactly five columns of 2-minute WSPR transmissions. The timestamp is always shown at the top right of the running program, or stamped on the bottom left of all saved images.
