### ISSUE TITLE
Hide out-of-band WSPRs

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#16]
Sometimes the WSPR Spot identifiers do not seem to align with corresponding traces.  Does not seem to be a consistent issue.  Perhaps it is the result of overlapping WSPR signals?  Also, I suspect it may be related to detected traces but WSJT-X did not decode the signal.

**Comment by swharden** [comment]
@K4RCG a screenshot here would be super helpful! I took a quick look at your latest grabber and things look all right. Although I'm very curious why the last column of WSPR spots isn't getting labeled 

![image](https://user-images.githubusercontent.com/4165489/86495153-25566200-bd46-11ea-96c7-d1cfd67b1b86.png)

**Comment by K4RCG** [comment]
Soctt, I find Win 10 often does not decode WSPR signals...probably 25% of the cycles, as evident in the grab.  Unlike my RasPi4B which decodes 100%.

**Comment by K4RCG** [comment]
I just edited my Isssue--not sure if you saw the tweaks.

**Comment by swharden** [comment]
I think I found an example of mislabeled WSPR codes

![image](https://user-images.githubusercontent.com/4165489/86495309-d9f08380-bd46-11ea-89cd-4237a5157a66.png)

Did you recently switch bands when this happened? My guess is it's showing some of the older 30m spots on your new 20m spectrogram. I'll fix this in an upcoming release, so only in-band WSPR spots will be labeled on the spectrogram 👍

**Comment by K4RCG** [comment]
Yes, I went from 30m to 20m.

**Comment by K4RCG** [comment]
Oppss..... 20m to 30m :-)

**Comment by swharden** [comment]
> Yes, I went from 20m to 30m.

Sounds like we found the problem! The issue will resolve after 10 minutes (which is why it looks good now), and I'll make sure this gets fixed in an upcoming release. I'll leave this issue open until I modify the code to fix it. Thanks for reporting this! 👍

**Comment by K4RCG** [comment]
:-)  I'm not trying to overload the issues tracker!!

**Comment by swharden** [comment]
> :-) I'm not trying to overload the issues tracker!!

No worries! I love having issue and feature conversations here, so the issues list can build (and collect resources like screenshots together), so when the day comes that I have the free time to attack all these ideas they're already neatly organized in a project-specific list. Keep 'em coming! 😎

**Comment by K4RCG** [comment]
Tnx!  I really like this tool.  I've been mentioning it and you on
WSPRnet.  When you deem appropriate, perhaps it would be fun to share it
there....would also expose QRSS to a larger audience.

Bob

**Comment by swharden** [comment]
> Tnx! I really like this tool. I've been mentioning it and you on WSPRnet. When you deem appropriate, perhaps it would be fun to share it there....would also expose QRSS to a larger audience. Bob

I'm not familiar with that group, but if it seems relevant go for it! 

On one hand it may be best to lie low for a few weeks while I iron out the kinks and work through the issues before we publicize it too much, but on the other hand if someone over there is a C# developer and would like to help me out with the programming I could really use the support, and it would be great to have additional sets of eyes looking over the code and helping implement these features! So, if you do mention it on another mailing list, consider also mentioning that its author is inviting discussion and contributions from C# developers!

**Comment by K4RCG** [comment]
Understood Scott.  I'll not offer it up for now.

Bob

**Comment by K4RCG** [comment]
I do know a Scottish and a German station are experimenting with the latest version.  Both are ardent WSPR OPRs.

**Comment by K4RCG** [comment]
Scott, here is a good example of how the one 10m WSPR spot did not align with the ID.
![Screenshot (13)](https://user-images.githubusercontent.com/67662141/86513780-79238280-bdfc-11ea-828f-2d716089816c.png)

**Comment by swharden** [comment]
I think this has been fixed with #10 and will appear in v1.0.5
