### ISSUE TITLE
Stand Alone De-Coder??

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#19]
Just a thought--not an issue.  Could FSKView adopt/adapt the WSJT decoder (e.g. JTDX, JS8Call) and become a 'stand alone'  WSPR/QRSS package?

**Comment by swharden** [comment]
Hey @K4RCG, this is a good idea and actually what I initially set-out to do with FSKview. I started making notes about the WSPR protocol, see my summary here https://swharden.com/software/FSKview/wspr.md.html

I eventually concluded that it's super complicated, and although perhaps I _could_ make a C# library to do this, WSTJ-X would undoubtedly do it better. That project has a team of experts behind it, and it's updated frequently, so I eventually decided just to let them do the part they're good at (decoding) and I'll keep FSKview light and simple and focused on _displaying_ spectrograms well.

**Comment by K4RCG** [comment]
Fully understand! I was as they say, “just sayin’...” LOL I was a wee bit
hesitant to make the suggestion, but thought it might actually be a good
idea and consistent with your objective to create an entry level QRSS
package for WIN.

On a related note, any thoughts of a companion piece that can transmit
various QRSS signals??

Bob

**Comment by swharden** [comment]
> On a related note, any thoughts of a companion piece that can transmit various QRSS signals?

Interesting suggestion! 🤔 I'll probably not do this, but a _separate_ program to transmit QRSS may be a useful application. I'll hang back and let another developer take this initiative though 🙃 I have quite a few projects on my plate!

**Comment by K4RCG** [comment]
Lol!! You are a busy guy!! I’ve been impressed...thank you so much for what
you are doing to help me and what you do for the hobby writ large.

Bob
