### ISSUE TITLE
"Upload Now" success dialogue is titled "ERROR"

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#22]
Oddity, I know...but the "Upload Now" button does not seem to work.  Also, a dialog box opens that says "Successful" but box itself is labled "Error".  Uploads at conclusion of 10min cycle seem OK.

**Comment by swharden** [comment]
> The "Upload Now" button does not seem to work. Also, a dialog box opens that says "Successful" but box itself is labled "Error". Uploads at conclusion of 10min cycle seem OK.

Hey @K4RCG, it sounds like the dialog box saying "successful" indicates the "upload now" button works.

Is the error you describe written in text on the bottom of FSKview, and could it be time-stamped to an old date (before you updated the settings in the settings dialogue)? If so, perhaps a good fix is to simply erase that label (which may show old error messages) whenever the settings dialog is opened

**Comment by K4RCG** [comment]
When pressing Upload Now, I get a dialog box that shows a "Red X" and "Error".  But text inside the box says "Successful".   LOL  No big deal; the Grabs are being uploaded judt fine.  Was just a simple oddity this morning when I was putting FSKV thru it's paces.

Bob

**Comment by swharden** [comment]
> When pressing Upload Now, I get a dialog box that shows a "Red X" and "Error". But text inside the box says "Successful". LOL No big deal; the Grabs are being uploaded judt fine. Was just a simple oddity this morning when I was putting FSKV thru it's paces.
> 
> Bob

Oh I see now, thanks! I'm so used to that dialog I'm blind to it now. The dialog box itself has an "ERROR" window title and shows a red X even if the FTP upload was a success - got it!

Note to self: if `result == "upload successful"` show a happy dialog window by modifying this line:

https://github.com/swharden/FSKview/blob/4f0a6e23afc57bf618d5d84314f41ca11f43dfaa/src/FSKview/FormSettings.cs#L89-L90

**Comment by K4RCG** [comment]
That's it!!  :-)

Bob

**Comment by swharden** [comment]
It looks like this now. Thanks again for the tip!

![image](https://user-images.githubusercontent.com/4165489/87227929-edfe3b80-c36b-11ea-9cca-e9c366832154.png)

**Comment by K4RCG** [comment]
Tnx!

Bob
