### ISSUE TITLE
Working Fine :-)

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#23]
Greetings Scott, no new issues/bugs have surfaced. Latest version seems to be stable and running fine.  I continue to test/run side-by-side with Argo.  Only continuing request I'd have would be the potential development of the companion TX function we previously discussed.  I think in doing so, a few more TX stations would become active and be an overall value-add for the QRSS  community. In my case, I'd love to TX but have been unable to find a Windows-based application that I can adapt/use with my rudimental PC skillset. I **_fully respect_** your previous comment that competition for your time/expertise would probably prevent development of a TX module.  As above,  FSKView is running great.  I'll continue testing a report any bugs/suggestions.  Once again, a HUGE THANK YOU for your contribution to the hobby,

73 Bob
K4RCG

**Comment by swharden** [comment]
Hey @K4RCG, this is great news! I've been running it for the last couple weeks and it seems to be holding up well on my end too. I'm happy it's remaining stable, and I'm excited to see what I'll be able to do with the 1000s of historical grabs saved in the "grabs-all" folder. 8hr grabs are cool, but what would a 1wk grab look like? My next round of work (whenever that happens) will probably be making tools aimed at analyzing those historical spectrograms.

**Comment by K4RCG** [comment]
Those new tools sound great.  QRSS is a great way to study propagation trends; I find myself looking at 'current" condx far too often.  I run FSKView daily....will let you know if I see anything.

Best regards
Bob
