### ISSUE TITLE
80 Meter Dial Freq

### ISSUE THREAD

**Issue by larryiweaver** [swharden/FSKview#24]
Currently the 80 meter dial freq is 3568600 Hz and FSKview ver 1.0.5 shows a dial freq of 3592600 Hz.

**Comment by swharden** [comment]
Hi @larryiweaver thanks for pointing that out! I drew my WSPR frequencies from those listed on http://wsprnet.org/drupal/node/218 (which cites http://www.g4ilo.com/wspr.html) Do you have a suggestion for an "official" source of WSPR frequencies I can refer to that may reflect the most updated and accurate list?

Note to self: WSPR band frequencies are defined here
https://github.com/swharden/FSKview/blob/4f0a6e23afc57bf618d5d84314f41ca11f43dfaa/src/FSKview/WsprBands.cs#L17-L29

**Comment by swharden** [comment]
... answering my own question, I found a list of frequencies on the front page of http://wsprnet.org/ so I'll make this change now. Thanks again for reporting this issue @larryiweaver!

![image](https://user-images.githubusercontent.com/4165489/87227401-b04be380-c368-11ea-9c32-c62d928853d9.png)
