### ISSUE TITLE
Brightness Level

### ISSUE THREAD

**Issue by larryiweaver** [swharden/FSKview#27]
It appears that FSKview does remember the brightness level on a restart but the drop down window reflects the default of 2. If click to reset the level I see the brightness level actually drop back to the default level of 2 at that time.

**Comment by swharden** [comment]
Hey @larryiweaver, thanks for reporting this! I took a closer look and it looks like brightness is getting saved in settings.xls, but it's not getting _loaded_ properly when FSKview starts. I'll fix this issue by the end of the weekend! 👍 

note to self edit this section:
https://github.com/swharden/FSKview/blob/53a6666ff1188ae085fbf53adb1328126f373d34/src/FSKview/FormMain.cs#L56-L62

to add a line like
```cs
nudBrightness.Value = settings.brightness;
```

**Comment by swharden** [comment]
Just fixed this. It'll be in version 1.0.7 released later tonight 👍
