### ISSUE TITLE
additional customization options

### ISSUE THREAD

**Issue by swharden** [swharden/FSKview#3]
add a mechanism to customize additional settings and remember GUI state through program restarts:

### Config File
- [x] create configuration system to save settings to a config file
- [x] continuously update config file so all GUI options persist through restarts

### Customizations
- [x] all current settings (colormap, autograb, intensity, sound card, etc)
- [x] autosave filename
- [x] station information
- [x] frequency offset adjustment
- [x] width (both _time span_ and _time resolution))
- [x] let user customize height (relative to band edges)
- [x] FTP details

**Comment by swharden** [comment]
I went with an XML format like this

```sml
<?xml version="1.0" encoding="utf-8"?>
<ProgramSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Version>1.0</Version>
  <audioDeviceIndex>0</audioDeviceIndex>
  <window>Cosine</window>
  <colormap>Viridis</colormap>
  <dialFrequencyIndex>5</dialFrequencyIndex>
  <brightness>2</brightness>
  <isWsprEnabled>true</isWsprEnabled>
  <wsprLogFilePath>asdf</wsprLogFilePath>
  <showBands>true</showBands>
  <saveGrabs>true</saveGrabs>
  <showScaleOnAllGrabs>false</showScaleOnAllGrabs>
  <grabFileName>latest.png</grabFileName>
  <targetWidth>1000</targetWidth>
  <grabSavePxAbove>123</grabSavePxAbove>
  <grabSavePxBelow>321</grabSavePxBelow>
  <verticalReduction>2</verticalReduction>
  <freqDisplayOffset>0</freqDisplayOffset>
  <grabMessage>station information not set</grabMessage>
  <ftpServerAddress>ftp://ftp.qsl.net</ftpServerAddress>
  <ftpRemoteSubfolder>/</ftpRemoteSubfolder>
  <ftpUsername>sampleUsername</ftpUsername>
  <ftpObfuscatedPassword>c2FUGcmQFzc3tcGxldv</ftpObfuscatedPassword>
  <ftpDelaySec>15</ftpDelaySec>
</ProgramSettings>
```

![image](https://user-images.githubusercontent.com/4165489/86502202-990c6500-bd6e-11ea-8b2b-4ac7ac6912f3.png)

**Comment by K4RCG** [comment]
Settings is a huge value-add. I especially like the RX above/below QRSS values....

**Comment by swharden** [comment]
done, will be in v1.0.5
