### ISSUE TITLE
Unsupported WSPR log line format

### ISSUE THREAD

**Issue by larryiweaver** [swharden/FSKview#30]
Hi Scott,
    This is the popup I get when I startup FSKview  7b.
![FSKview_cap](https://user-images.githubusercontent.com/67514082/88496355-e1442f00-cf8a-11ea-9549-47eadf2616c0.JPG)

Larry

**Comment by larryiweaver** [comment]
It appears to run OK after clicking on "Continue"

**Comment by swharden** [comment]
Interesting! Can you upload the log file you are trying to view? Thanks!

**Comment by swharden** [comment]
resolved, will be in FSKview 1.0.8 uploaded in a few minutes...
