### ISSUE TITLE
FT4/FT8 audio frequency offset

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#32]
![image](https://user-images.githubusercontent.com/67662141/88739728-c3153500-d12a-11ea-878c-b3b4a60fd27e.png)

Scott, attached is a screenshot.  The Callsigns are listed but unable to "link" them to a trace.

Bob K4RCG

**Comment by swharden** [comment]
Hey Bob! I took a closer look and think I figured it out. Let's use this log line as an example

```
191010_125753    14.080 Rx FT4    -10 -0.1 1730 AI2I KM4UJI -17
                 ^^^^^^                    ^^^^
```

The first frequency is the _dial_ frequency in MHz. This is what FSKview is currently using for each FT4/8 frequency. However, the second frequency indicated is the _audio_ frequency in Hz. For FT4/FT8 logs (as opposed to WSPR logs) the _actual_ frequency should be:

```
14.080 MHz + 1730 Hz = 14,081,730 Hz
```

I updated FSKview to add these two numbers together and display the label at that frequency. Let's see if this works! 🤞 I made a new version of this program containing this change: https://swharden.com/software/FSKview/downloads/FSKview-1.0.9.zip

Let me know if this works for you!
