### ISSUE TITLE
V 1.0.10 IT WORKS!

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#37]
Look at the DX on 30m! 

BRAVO Scott!  Tnx for adding a new tool to my inventory!!
![Screenshot (18)](https://user-images.githubusercontent.com/67662141/89032241-c7587280-d323-11ea-9de1-cf469f968e1c.png)

73 de Bob K4RCG

**Comment by K4RCG** [comment]
Here is a WSPR shot Scott.  I think the real utility of FSKViewer is your original intent....monitor/display QRSS and WSPR due to time frames/freq proximity.  I really like your app.  I plan to continue running and uploadng grabs. WELL DONE!

73 de Bob
K4RCG
![Screenshot (19)](https://user-images.githubusercontent.com/67662141/89033573-99286200-d326-11ea-837f-3cebefac45d6.png)

**Comment by swharden** [comment]
Fantastic news! Thanks for the follow-up! These screenshots are so cool to see 😄
