### ISSUE TITLE
Vertical Reduction

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#39]
Is it possible to add 3x and 4x options to Vertical Reduction?

73 de K4RCG
Bob

**Comment by K4RCG** [comment]
[
![Screenshot (20)](https://user-images.githubusercontent.com/67662141/89122677-cd338c80-d4b8-11ea-9e2d-e033f6e8d680.png)
](url)

**Comment by swharden** [comment]
It'll require a new settings file (can't use the old one), but it seems to work now!

Version 1.1.2 
https://swharden.com/software/FSKview/#latest-version

Let me know what you think!

![image](https://user-images.githubusercontent.com/4165489/89484030-87eab580-d76b-11ea-8234-97fffe5ff1a3.png)

**Comment by swharden** [comment]
![image](https://user-images.githubusercontent.com/4165489/89484086-acdf2880-d76b-11ea-8490-cb4f9806762a.png)

**Comment by df2jp** [comment]
Hi, Scott and group,

I found a "bad" bug. 
In FT8 not the received calls but the called ones are displayed.
The schema is the same as in SSB or CW.
Call de Caller, so the second callsign must be displayed

For the selected spots, for example CT1DHR calls for ZL1BRL. 
But I only hear CT1DHR, which then has to be labelled.

73 Joe

**Comment by K4RCG** [comment]
Guten Morgen Joe,

Good “catch”! Scott is working on this app and we’ll see what it
continues to do.   I really like being able to identify digi mode traces by
callsigns. I think this is a very cool feature in addition to QRSS.

A thought Scott: *IF* QRSS Tx stations added some sort of digital ID bits
to their signals we could have call their signs superimposed on the QRSS
traces as well. This would be great to identify QRSS signals without
stacking. I wonder if the Reed Solomon ID protocol from other digi modes
could be a clue??  Or maybe just what WSJT USES?? Ha, I’m making this all
too complex!!!  Easy for me to suggest work!!! LOL

73
Bob

**Comment by swharden** [comment]
> In FT8 ... CT1DHR calls for ZL1BRL. But I only hear CT1DHR

Thanks for reporting this Joe! Consider this FT8 log line:

```
191010_124800     7.074 Rx FT8    -14  0.1 2066 KG5JJ W4POT EL99
```

Currently the first word after the audio offset (`2066`) is what is displayed in FSKview. It sounds like you'd like all words after the offset to be displayed instead. For this line, that would be `KG5JJ W4POT EL99` not just `KG5JJ`. I will make this change this evening.

Bob I like your idea (having QRSS TX'ers transmit a digital ID), but it seems unlikely to happen as it would mean reprogramming all the QRSS transmitters out there to transmit some new mode. For QRSS I think we're pretty entrenched transmitting only FSK CW, with the occasional animal on the spectrogram here and there =]

**Comment by swharden** [comment]
I'll leave this issue closed and track progress toward Joe's suggestion in issue #40

**Comment by K4RCG** [comment]
Concur Scott!  The random balloons and animals will suffice!  :-)

Bob

**Comment by swharden** [comment]
FYI, Joe, the full message should now be displayed in version 1.1.3
https://swharden.com/software/FSKview/#latest-version

Feel free to post here or in #40 if you have any trouble!
Scott
