### ISSUE TITLE
integrate FTP uploader into FSKview

### ISSUE THREAD

**Issue by swharden** [swharden/FSKview#4]
Right now QRSS Uploader is its own program (https://github.com/swharden/QRSS-Uploader).

The reason for this is I can make feature changes to FSKview without risking the FTP upload component, and vise-versa (spectrogram formation and FTP uploading are two separate tasks).

That said, it would be convenient to have both programs in one, so after FSKview development slows down build a FTP uploader into it.

**Comment by K4RCG** [comment]
Makes sense to me!

**Comment by swharden** [comment]
done, this will be in v1.0.5

**Comment by K4RCG** [comment]
I think this will make it easier for computer skills limited people like me
to get their grabs uploaded.  That Settings box will be nice. Eager to try
1.05 when it’s released.

Bob
