### ISSUE TITLE
Improve FT4/8 text placement

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#42]
Scott, BRAVO for attempting to add FT8 trace identification, but the screen is just too busy.  One decode cycle I saw 70+ FT8 callsigns.  V 1.1.3 is working, but I'm not sure the additional capability it provides yields much value in terms of dat than can be turned in actionable inofmation.  Thoughts??

Best Regards/73
Bob K4RCG

**Comment by swharden** [comment]
What if rather than using numbers 1, 2, 3, etc. we just write the transmission right where it appears on the spectrogram?

**Comment by K4RCG** [comment]
That may work.   Would that be a difficult tweak for you to make?

Bob

**Comment by swharden** [comment]
Want to give 1.1.4 a try? If you could send a screenshot back that would be great! I don't run a FT4/8 receiver so I'm interested to learn how this looks on your screen

https://swharden.com/software/FSKview/#latest-version

Thanks!

**Comment by K4RCG** [comment]
Sure thing Scott. I should be active later today; grass cutting and run to
the local co-op for chicken feed today!  Rural life!!

Bob

**Comment by K4RCG** [comment]
Screenshot from 1.1.4 Scott.  This is WSPR.  Will try FT8 next.
![Screenshot (22)](https://user-images.githubusercontent.com/67662141/89843101-0af27e00-db67-11ea-855b-3153b0df189f.png)

**Comment by K4RCG** [comment]
Here is FT8. 
![Screenshot (23)](https://user-images.githubusercontent.com/67662141/89843404-18f4ce80-db68-11ea-89fd-da661094cf38.png)

**Comment by swharden** [comment]
lol! After all that, I agree. FSKview is designed to view FSK signals ~10 minutes wide. It's not really designed for FSK transmission of short durations like FT4/8, so it was a good try but probably the best thing to do from here is to remove FT4/8 support 🤔 

The WSJT-X team can be encouraged to make a more feature rich spectrogram 😄 

Thanks for all your tips and suggestions along the way though!

**Comment by K4RCG** [comment]
I agree 100% Scott.  You get the "A" for effort, undoubtedly!!  But the
real good news is that FSKView has added value to QRSS and WSPR.  Thank you
for your significant effort.  WELL DONE!!

Bob K4RCG

**Comment by swharden** [comment]
We both get As for effort on this one 😄 thanks for you help testing along the way!

**Comment by K4RCG** [comment]
WHEN you get another great idea, please add me to your Beta team!!!

Bob
