### ISSUE TITLE
WSPR spot labels do not align with the spots themselves

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#44]
WSPR Trace IDs are once again not aligning with the actual Trace.    

Bob K4RCG

**Comment by K4RCG** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/67662141/90688391-edf03600-e25d-11ea-9516-93499d5dfa6a.png)

**Comment by swharden** [comment]
Hi Bob, the intended display is like this, with all WSPR traces at the top. This helps prevent overlap because WSPR traces are more dense than the labels (this is why numbers are used)

![image](https://user-images.githubusercontent.com/4165489/90688341-53332f80-e23c-11ea-8d85-998abb4d3de3.png)

**Comment by K4RCG** [comment]
Understood, but my problem is that the numbers do not align with
traces...i.e. they do not superimpose on the trace.

Bob

**Comment by swharden** [comment]
My bad Bob, I misunderstood your initial description. I think the problem here is that your dial frequency doesn't exactly match what it should be - looks 30Hz off to me!

**Comment by K4RCG** [comment]
Ahhhh....  good catch!!  Calibration issue affecting the ID placement!

TNX!!!!

Bob

**Comment by K4RCG** [comment]
That’s definitely my problem! My rig calibration is off a wee bit. I
typically tune off my desired frequency by a few Hz to center QRSS in the
band. After you mentioned that may be my trace ID issue, I’ve been trying
to use the Calibration function
to address that issue.

I’m involved with a Scottish WSPR group and we will be doing propagation
tests tonight on 30m. Additionally, participants will be looking at their
WSPR traces using your FSKview app. Good stuff!’

73
Bob K4RCG
