### ISSUE TITLE
password using FSKView 1.1.7

### ISSUE THREAD

**Issue by allydog** [swharden/FSKview#45]
I am having a problem dealing with the password in FSKView.  I see the one in the settings.xml but it does not work, what am I doing wrong. It seems the only one you can use is what is in the settings.xml, correct ?  Yet when I do use that PW,  all it says is  INCORRECT USERNAME/PASSWORD.
I had other issues, but got them figured out, but that this one.

**Comment by allydog** [comment]
Looks like I got the answer in groups.io , qrssknights.

**Comment by swharden** [comment]
> Looks like I got the answer in https://groups.io/g/qrssknights

```
Welcome to Knights Al.
You don't need to use those settings unless you decide to upload your grabs to a website.

If at some time you think that you'd like to become an online grabber, then you can upload
each grab automatically, to your own website.

Many of us just open an qsl.net account and upload the files to it.

If a grabber seems to be doing good public service then one of us will add it to the
AJ4VD compendium.

73/4 de Andy
```
