### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by swharden** [swharden/FSKview#6]
can this program be run with multiple sound cards simultaneously?

**Comment by K4RCG** [comment]
Time permiting, I'll test and see.  I suspect it will work.  I use multiple instances of WSJT-X all the time.  Only problem might be the All_WSPR.txt path.  I had some difficulty getting FSKView to run (initially) and surmise it was a path problem.

**Comment by K4RCG** [comment]
I tested running two instances with different audio streams.  Suprisingly, I could not get it to work despite WSJT-X and Argo running fine in that configuration.  Two instances of FSKView will run using the same sound stream, but I don't see a need for that.

**Comment by swharden** [comment]
Two instances of the same FSKview.exe are running well on my system using two different audio inputs

Importantly, to use them as grabbers they must be configured to save with different filenames (arrow)

Since this is tested/working, I'll close this issue

![image](https://user-images.githubusercontent.com/4165489/86475979-a0eaeb80-bd13-11ea-9bad-b783c171fb31.png)
