### ISSUE TITLE
WSPR Spots Not Showing

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#8]
Loaded 1.04b(1); initially wouldn't run.  Now running after re-installation, but WSPR sports not showing.

**Comment by swharden** [comment]
Make sure WSJT-X is running and logging WSPR spots. Verify the `ALL_WSPR.TXT` file it produces to ensure it contains spots generated within the last 10 minutes.

https://physics.princeton.edu/pulsar/K1JT/wsjtx.html

Then in FSKview, click the "configure" button and navigate to the location of the `ALL_WSPR.TXT` file. Once that file is selected in FSKview, spots should appear on the spectrum. Let me know if this does the trick! 👍

**Comment by K4RCG** [comment]
Tnx Vern.  I'm QRT today due to T Storms.  I'll start re-testing soonest.  I'm sure it has something to do with the multiple instances of WSJT-run for WSPR spotting and the path to the .txt file being corrupted.

Bob K4RCG

**Comment by K4RCG** [comment]
I'm sorry.....SCOTT, not Vern!  Senior moment!!!  :-)

**Comment by swharden** [comment]
No worries! I'll leave this issue "open" until we have it resolved with confidence 😎

**Comment by K4RCG** [comment]
Tnx Scott! I don’t do much ham radio when T Storms are about!  I currently
off the air.

I am sure it’s a .txt path problem. I run multiple instances of WSJT-X when
operating the full SDR bank. I recently upgraded to v2.2.2 and suspect I’ve
managed to create some collisions!

Oddly, I had FSKView working fine at one point; now the gremlins have
set-up residence!

Bob K4RCG

**Comment by swharden** [comment]
>  I had FSKView working fine at one point; now the gremlins have set-up residence! 

Those temperamental software gremlins are the worst! They sneak in with updates 😈 

I'd probably start by double-checking the path that the new WSJT-X is saving the `ALL_WSPR.TXT` file using the WSJT-X program itself. Open that text file in notepad too and ensure the spots there are recent (within the last 10 minutes).

Then in FSKview, click the `configure` button and ensure FSKview is pointing to _that_ text file (not an old one in another folder).

Hope it helps!

**Comment by K4RCG** [comment]
Fixed All_WSPR/txt path and spots show.  :-)
